=== ChristianHinkle/Timeliner/TimelineFileFormat/tmln_schema.json
{
    "$id": "https://raw.githubusercontent.com/ChristianHinkle/Timeliner/refs/heads/main/TimelineFileFormat/tmln_schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "refs": {
            "type": "object",
            "properties": {
                "entities": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "identifier": {
                                "type": "string"
                            }
                        },
                        "required": ["identifier"]
                    }
                },
                "animClips": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "identifier": {
                                "type": "string"
                            }
                        },
                        "required": ["identifier"]
                    }
                },
                "audioClips": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "identifier": {
                                "type": "string"
                            }
                        },
                        "required": ["identifier"]
                    }
                }
            }
        },
        "timing": {
            "type": "object",
            "properties": {
                "fps": {
                    "type": "integer",
                    "minimum": 0
                },
                "end": {
                    "type": "integer",
                    "minimum": 1
                }
            },
            "required": ["fps", "end"]
        },
        "tracks": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "subtracks": {
                        "type": "array"
                    }
                },
                "required": ["id", "type"]
            }
        },
        "keys": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "frame": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "tracks": {
                        "type": "array"
                    }
                },
                "required": ["frame", "tracks"]
            }
        }
    },
    "required": ["timing"]
}

=== ChristianHinkle/Timeliner/FileExamples/ExampleC_AudioClip.tmln.json
{
    "refs": {
        "entities": [
            {
                "identifier": "PlayerCharacter"
            }
        ],
        "audioClips": [
            {
                "identifier": "PlayerCharacter_Shout"
            }
        ]
    },
    "timing": {
        "fps": 24,
        "end": 96
    },
    "tracks": [
        {
            "id": "PlayerCharacter",
            "type": "entity",
            "entityRef": "PlayerCharacter",
            "subtracks": [
                {
                    "id": "AudioEmitter",
                    "type": "audioEmitter",
                    "subtracks": [
                        {
                            "id": "AudioClipOperation",
                            "type": "audioClipOperation"
                        }
                    ]
                }
            ]
        }
    ],
    "keys": [
        {
            "frame": 1,
            "tracks": [
                {
                    "id": "PlayerCharacter",
                    "subtracks": [
                        {
                            "id": "AudioEmitter",
                            "subtracks": [
                                {
                                    "id": "AudioClipOperation",
                                    "value": {
                                        "type": "reset"
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "frame": 12,
            "tracks": [
                {
                    "id": "PlayerCharacter",
                    "subtracks": [
                        {
                            "id": "AudioEmitter",
                            "subtracks": [
                                {
                                    "id": "AudioClipOperation",
                                    "value": {
                                        "type": "play",
                                        "audioClipRef": "PlayerCharacter_Shout",
                                        "rate": 1.0000000000000000
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== ChristianHinkle/Timeliner/FileExamples/ExampleB_AnimClip.tmln.json
{
    "refs": {
        "entities": [
            {
                "identifier": "PlayerCharacter"
            },
            {
                "identifier": "PlayerWeapon"
            }
        ],
        "animClips": [
            {
                "identifier": "PlayerCharacter_FirePistol"
            },
            {
                "identifier": "PlayerWeapon_FirePistol"
            }
        ]
    },
    "timing": {
        "fps": 24,
        "end": 96
    },
    "tracks": [
        {
            "id": "PlayerCharacter",
            "type": "entity",
            "entityRef": "PlayerCharacter",
            "subtracks": [
                {
                    "id": "Mesh",
                    "type": "mesh",
                    "subtracks": [
                        {
                            "id": "AnimClipOperation",
                            "type": "animClipOperation"
                        }
                    ]
                }
            ]
        },
        {
            "id": "PlayerWeapon",
            "type": "entity",
            "entityRef": "PlayerWeapon"
        }
    ],
    "keys": [
        {
            "frame": 1,
            "tracks": [
                {
                    "id": "PlayerCharacter",
                    "subtracks": [
                        {
                            "id": "Mesh",
                            "subtracks": [
                                {
                                    "id": "AnimClipOperation",
                                    "value": {
                                        "type": "reset"
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "frame": 12,
            "tracks": [
                {
                    "id": "PlayerCharacter",
                    "subtracks": [
                        {
                            "id": "Mesh",
                            "subtracks": [
                                {
                                    "id": "AnimClipOperation",
                                    "value": {
                                        "type": "play",
                                        "animClipRef": "PlayerCharacter_FirePistol",
                                        "rate": 1.0000000000000000
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== ChristianHinkle/Timeliner/FileExamples/ExampleA_EntityTransform.tmln.json
{
    "refs": {
        "entities": [
            {
                "identifier": "PlayerCharacter"
            },
            {
                "identifier": "PlayerWeapon"
            }
        ]
    },
    "timing": {
        "fps": 24,
        "end": 24
    },
    "tracks": [
        {
            "id": "PlayerCharacter",
            "type": "entity",
            "entityRef": "PlayerCharacter",
            "subtracks": [
                {
                    "id": "Transform",
                    "type": "transform",
                    "subtracks": [
                        {
                            "id": "Translation",
                            "type": "double3",
                            "subtracks": [
                                {
                                    "id": "x",
                                    "type": "double"
                                },
                                {
                                    "id": "y",
                                    "type": "double"
                                },
                                {
                                    "id": "z",
                                    "type": "double"
                                }
                            ]
                        },
                        {
                            "id": "Rotation",
                            "type": "double4",
                            "subtracks": [
                                {
                                    "id": "x",
                                    "type": "double"
                                },
                                {
                                    "id": "y",
                                    "type": "double"
                                },
                                {
                                    "id": "z",
                                    "type": "double"
                                },
                                {
                                    "id": "w",
                                    "type": "double"
                                }
                            ]
                        },
                        {
                            "id": "Scale",
                            "type": "double3",
                            "subtracks": [
                                {
                                    "id": "x",
                                    "type": "double"
                                },
                                {
                                    "id": "y",
                                    "type": "double"
                                },
                                {
                                    "id": "z",
                                    "type": "double"
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "id": "PlayerWeapon",
            "type": "entity",
            "entityRef": "PlayerWeapon"
        }
    ],
    "keys": [
        {
            "frame": 1,
            "tracks": [
                {
                    "id": "PlayerCharacter",
                    "subtracks": [
                        {
                            "id": "Transform",
                            "subtracks": [
                                {
                                    "id": "Translation",
                                    "subtracks": [
                                        {
                                            "id": "x",
                                            "value": 0.0000000000000000
                                        },
                                        {
                                            "id": "y",
                                            "value": 0.0000000000000000
                                        },
                                        {
                                            "id": "z",
                                            "value": 0.0000000000000000
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "frame": 24,
            "tracks": [
                {
                    "id": "PlayerCharacter",
                    "subtracks": [
                        {
                            "id": "Transform",
                            "subtracks": [
                                {
                                    "id": "Translation",
                                    "subtracks": [
                                        {
                                            "id": "x",
                                            "value": 0.0000000000000000
                                        },
                                        {
                                            "id": "y",
                                            "value": 100.00000000000000
                                        },
                                        {
                                            "id": "z",
                                            "value": 0.0000000000000000
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
